{{- $valid := list "DEBUG" "INFO" "WARNING" "ERROR" "CRITICAL" -}}
{{- if not (has .Values.prom2teams.loglevel $valid) -}}
{{- fail "Invalid log level"}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom2teams-config
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.ini: |-
    [HTTP Server]
    Host: {{ .Values.prom2teams.host }}
    Port: {{ .Values.prom2teams.port }}
    [Microsoft Teams]
    {{- with .Values.prom2teams.connector }}
    Connector: {{ . }}
    {{- end }}
    {{- range $key, $val := .Values.prom2teams.connectors }}
    {{ $key }}: {{ $val }}
    {{- end }}
    [Group Alerts]
    Field: {{ .Values.prom2teams.group_alerts_by }}
    [Log]
    Level: {{ .Values.prom2teams.loglevel }}
    [Template]
    Path: {{ .Values.prom2teams.templatepath }}
  teams.j2: {{ .Files.Get "files/teams.j2" |  quote }}